version: "3.7"
services:
  client:
    depends_on:
      - server
    build:
      context: ./http-log-client
    environment:
      - PYTHONUNBUFFERED=1
    network_mode: host
    command: "--port=8001"
  server:
    build:
      context: ./http-log-server
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8001:8001"
    network_mode: host
    command: "--port=8001"
