version: "3.7"
services:
  client:
    depends_on:
      - server
    build:
      context: ./http-log-client
    network_mode: host
    command: "--port=8001"

  server:
    build:
      context: ./http-log-server
    ports:
      - "8001:8001"
    network_mode: host
    command: "--tcp_onoff=True --port=8001"
