version: "3.7"
services:
  client:
    depends_on:
      - server
    build:
      context: ./http-log-client
    network_mode: host

  server:
    build:
      context: ./http-log-server
    ports:
      - "8001:8001"
    network_mode: host
