apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: "mysql"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      # initContainers:
      #   - name: init-mysql
      #     image: busybox
      #     command: ['sh', '-c', 'chmod 777 /var/lib/mysql']
      #     volumeMounts:
      #     - mountPath: /var/lib/mysql
      #       name: mydata
      containers:
        - image: mysql
          name: mysql
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flaskapi-secrets
                  key: db_root_password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
          # resources:
          #   requests:
          #     cpu: 2000m
          #     memory: 2Gi
          #   limits:
          #     cpu: 4000m
          #     memory: 4Gi
      # volumes:
      #   - name: mysql-persistent-storage
      #     persistentVolumeClaim:
      #       claimName: mysql-pv-claim
      volumes:
        - name: mysql-persistent-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: db
spec:
  ports:
    - port: 3306
      protocol: TCP
      name: mysql
  selector:
    app: db
  type: NodePort
