apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-log-server
  labels:
    app: http-log-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-log-server
  template:
    metadata:
      labels:
        app: http-log-server
    spec:
      containers:
        - name: http-log-server
          image: lptonussi/public:http-log-server
          imagePullPolicy: Always
          args: [
            '--address=localhost',
            '--port=8001',
            "--buffer_size=1024",
            "--tcp_onoff=False"
          ]
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: http-server-logs
              mountPath: /tmp/logs
          ports:
            - containerPort: 8001
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          # readinessProbe:
          #   tcpSocket:
          #     port: 8001
          livenessProbe:
            exec:
              command:
                - curl
                - -X POST
                - http://localhost/
      restartPolicy: Always
      volumes:
        - name: http-server-logs
          emptyDir: {}
      nodeSelector:
        "kubernetes.io/role": "landowner"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: name
                    operator: In
                    values: [ "http-log-server" ]
              topologyKey: failure-domain.beta.kubernetes.io/zone
---
apiVersion: v1
kind: Service
metadata:
  name: http-log-server
spec:
  ports:
    - name: http
      port: 8001
      protocol: TCP
      targetPort: 8001
  selector:
    app: http-log-server
  type: NodePort
