apiVersion: apps/v1
# kind: StatefulSet
kind: Deployment
metadata:
  name: http-log-server
  labels:
    app: http-log-server
spec:
  # serviceName: "http-log-server"
  replicas: 1
  selector:
    matchLabels:
      app: http-log-server
  template:
    metadata:
      labels:
        app: http-log-server
    spec:
      containers:
        - name: http-log-server
          image: lptonussi/http-log-server
          imagePullPolicy: Always
          args: [
            '--port=$PORT'
          ]
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 8001
          resources:
            requests:
              memory: "300Mi"
              cpu: "50m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      restartPolicy: Always
      nodeSelector:
        role: server
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: name
                    operator: In
                    values: [ "http-log-server" ]
              topologyKey: failure-domain.beta.kubernetes.io/zone
---
apiVersion: v1
kind: Service
metadata:
  name: http-log-server
spec:
  ports:
    - name: http
      port: 8001
      targetPort: 8001
  selector:
    app: http-log-server
  type: NodePort
